### ISSUE TITLE
UnavailableInvalidChannel: The channel is not accessible or is invalid.

### ISSUE THREAD

**Issue by Shegun93** [facebookresearch/ContrastiveSceneContexts#21]
Hi thanks for this repo.
I was following the installation however when i go `conda install -c bioconda google-sparsehash` i got an error 
here's the log
Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: bioconda
  channel url: https://conda.anaconda.org/bioconda
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.

**Comment by Sekunde** [comment]
Hi, 
I can not reproduce your issue, please make sure your internet connection works for the bioconda channel.

my log:
(base) rohan :: ~ » conda install -c bioconda google-sparsehash
Collecting package metadata (current_repodata.json): done
Solving environment: -
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistenc\

  - defaults/linux-64::jupyter==1.0.0=py38_7
  - defaults/noarch::nltk==3.5=py_0
  - defaults/linux-64::conda-build==3.18.11=py38_0
  - defaults/linux-64::mkl_fft==1.1.0=py38h23d657b_0
  - defaults/linux-64::matplotlib==3.2.2=0

**Comment by Shegun93** [comment]
Hi Sekunde,
thanks for the help, I have been able to solve that and moved past it however, I have a new challenge I will appreciate you help me take a look.

while trying to run the code `python setup.py build_ext --include-dirs=YOUR_ENV_PATH/include
` I do not specifically understand what you meant by [YOUR_ENV_PATH/include] are you talking about my cuda path or a virtual environment created for it. I tried the two here's is the error

my log
(sparseconv043) segun@segun-HP-Pavilion-Notebook:~/downstream/insseg/lib/bfs/ops$ python setup.py build_ext --include-dirs=/anaconda3/envs/sparseconv043/include
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
running build_ext
building 'PG_OP' extension
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    cmdclass={'build_ext': BuildExtension}
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 603, in build_extensions
    build_ext.build_extensions(self)
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
    cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 337, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1325, in _get_cuda_arch_flags
    capability = torch.cuda.get_device_capability()
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/cuda/__init__.py", line 273, in get_device_capability
    prop = get_device_properties(device)
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/cuda/__init__.py", line 278, in get_device_properties
    _lazy_init()  # will define _get_device_properties and _CudaDeviceProperties
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/cuda/__init__.py", line 149, in _lazy_init
    _check_driver()
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/cuda/__init__.py", line 63, in _check_driver
    of the CUDA driver.""".format(str(torch._C._cuda_getDriverVersion())))
AssertionError: 
The NVIDIA driver on your system is too old (found version 10010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version

please how do I navigate through it.
once again thank you

**Comment by Sekunde** [comment]
Hi, I mean the virtual environment path created for it, e.g.,  in my case it looks like this:

python setup.py build_ext --include-dirs=/rhome/jhou/.local/anaconda3/envs/sparseconv043/include

**Comment by Shegun93** [comment]
Thanks so much for the prompt response. 
I tried to run the python script again but gotten the same error.

here's log

(sparseconv043) segun@segun-HP-Pavilion-Notebook:~/downstream/insseg/lib/bfs/ops$ python setup.py build_ext --include-dirs=/anaconda3/envs/sparseconv043/include
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
running build_ext
building 'PG_OP' extension
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    cmdclass={'build_ext': BuildExtension}
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 603, in build_extensions
    build_ext.build_extensions(self)
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
    cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 337, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1325, in _get_cuda_arch_flags
    capability = torch.cuda.get_device_capability()
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/cuda/__init__.py", line 273, in get_device_capability
    prop = get_device_properties(device)
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/cuda/__init__.py", line 278, in get_device_properties
    _lazy_init()  # will define _get_device_properties and _CudaDeviceProperties
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/cuda/__init__.py", line 149, in _lazy_init
    _check_driver()
  File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/cuda/__init__.py", line 63, in _check_driver
    of the CUDA driver.""".format(str(torch._C._cuda_getDriverVersion())))
AssertionError: 
The NVIDIA driver on your system is too old (found version 10010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

CUDA version
`nvcc -V`
(sparseconv043) segun@segun-HP-Pavilion-Notebook:~/downstream/insseg/lib/bfs/ops$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

`nvidia-smi`

Fri Nov 12 14:38:06 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.226.00   Driver Version: 418.226.00   CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 960M    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   49C    P5    N/A /  N/A |    375MiB /  4043MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1106      G   /usr/lib/xorg/Xorg                            24MiB |
|    0      1323      G   /usr/bin/gnome-shell                          48MiB |
|    0      3346      G   /usr/lib/xorg/Xorg                           117MiB |
|    0      3527      G   /usr/bin/gnome-shell                          79MiB |
|    0      6223      G   ...AAgAAAAAAAAACAAAAAAAAAA= --shared-files   100MiB |
+-----------------------------------------------------------------------------+

**Comment by Shegun93** [comment]
> Thanks so much for the prompt response. I tried to run the python script again but gotten the same error.
> 
> here's log
> 
> (sparseconv043) segun@segun-HP-Pavilion-Notebook:~/downstream/insseg/lib/bfs/ops$ python setup.py build_ext --include-dirs=/anaconda3/envs/sparseconv043/include No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda' running build_ext building 'PG_OP' extension Traceback (most recent call last): File "setup.py", line 12, in cmdclass={'build_ext': BuildExtension} File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/setuptools/**init**.py", line 153, in setup return distutils.core.setup(**attrs) File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/core.py", line 148, in setup dist.run_commands() File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/dist.py", line 966, in run_commands self.run_command(cmd) File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/dist.py", line 985, in run_command cmd_obj.run() File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run _build_ext.run(self) File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/command/build_ext.py", line 340, in run self.build_extensions() File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 603, in build_extensions build_ext.build_extensions(self) File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions self._build_extensions_serial() File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial self.build_extension(ext) File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension _build_ext.build_extension(self, ext) File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension depends=ext.depends) File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile cuda_post_cflags = unix_cuda_flags(cuda_post_cflags) File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 337, in unix_cuda_flags cflags + _get_cuda_arch_flags(cflags)) File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1325, in _get_cuda_arch_flags capability = torch.cuda.get_device_capability() File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/cuda/**init**.py", line 273, in get_device_capability prop = get_device_properties(device) File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/cuda/**init**.py", line 278, in get_device_properties _lazy_init() # will define _get_device_properties and _CudaDeviceProperties File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/cuda/**init**.py", line 149, in _lazy_init _check_driver() File "/home/segun/anaconda3/envs/sparseconv043/lib/python3.7/site-packages/torch/cuda/**init**.py", line 63, in _check_driver of the CUDA driver.""".format(str(torch._C._cuda_getDriverVersion()))) AssertionError: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.
> 
> CUDA version `nvcc -V` (sparseconv043) segun@segun-HP-Pavilion-Notebook:~/downstream/insseg/lib/bfs/ops$ nvcc -V nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2019 NVIDIA Corporation Built on Sun_Jul_28_19:07:16_PDT_2019 Cuda compilation tools, release 10.1, V10.1.243
> 
> `nvidia-smi`
> 
> Fri Nov 12 14:38:06 2021 +-----------------------------------------------------------------------------+ | NVIDIA-SMI 418.226.00 Driver Version: 418.226.00 CUDA Version: 10.1 | |-------------------------------+----------------------+----------------------+ | GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC | | Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. | |===============================+======================+======================| | 0 GeForce GTX 960M Off | 00000000:01:00.0 Off | N/A | | N/A 49C P5 N/A / N/A | 375MiB / 4043MiB | 2% Default | +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+ | Processes: GPU Memory | | GPU PID Type Process name Usage | |=============================================================================| | 0 1106 G /usr/lib/xorg/Xorg 24MiB | | 0 1323 G /usr/bin/gnome-shell 48MiB | | 0 3346 G /usr/lib/xorg/Xorg 117MiB | | 0 3527 G /usr/bin/gnome-shell 79MiB | | 0 6223 G ...AAgAAAAAAAAACAAAAAAAAAA= --shared-files 100MiB | +-----------------------------------------------------------------------------+

please help me look into it. i followed the installation up till where im now

**Comment by Sekunde** [comment]
Hi, it seems your Nvidia driver is too old, please upgrade it. And with GTX960M (4g mem,) you may not be able to even load the model, maybe you can consider using a larger GPU.
